# TensorFlow 101

### 1. Basic syntax
### 2. TensorFlow Graphs
### 3. tf.Variable
### 4. tf.Placeholder
### 5. TensorFlow Neural Network
### 6. TensorFlow Regression and Classification
### 7. Estimator API
### 8. Saving and Restoring Model

## 1. Basic syntax

#### Version

In [71]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.8.0


Tensor (Hello World)

In [73]:
hello = tf.constant("hello ")

In [6]:
world = tf.constant("world")

In [75]:
type(hello)

tensorflow.python.framework.ops.Tensor

#### Session:

In [8]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [9]:
print(result)

b'hello world'


#### matrix multiplication

In [10]:
a = tf.constant( [ [1,2], [3,4] ])

In [11]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [12]:
b = tf.constant( [ [1], [2] ])

In [13]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [18]:
ab = tf.matmul(a, b)

In [22]:
with tf.Session() as sess:
    result = sess.run(ab)
print(result)

[[ 5]
 [11]]


In [25]:
sess = tf.InteractiveSession()

In [26]:
ab.eval()

array([[ 5],
       [11]], dtype=int32)

## 2. TensorFlow Graphs

Graphs are sets of connected nodes.  
In TensorFlow each node is an operation with possible inputs that can supply some output.

Build Graph

![caption](img/graph_example.png)

In [29]:
n1 = tf.constant(1)
n2 = tf.constant(2)

In [30]:
n3 = n1 + n2

In [31]:
with tf.Session() as sess:
    result = sess.run(n3)

In [32]:
print(n3)

Tensor("add_1:0", shape=(), dtype=int32)


In [33]:
print(tf.get_default_graph())

In [34]:
g = tf.Graph()

In [35]:
print(g)

In [36]:
graph_one = tf.get_default_graph()

In [37]:
print(graph_one)

In [39]:
with g.as_default():
    print(g is tf.get_default_graph())

True


In [40]:
print(g is tf.get_default_graph())

False


## 3. Variables

* During the optimization process, TensorFlow tunes the parameters of the model
* Variables can hold the values of weights and biases throughout the session
* Variables need to be initialized


What is the lifetime of a variable?

A variable is created when you first run the tf.Variable.initializer operation for that variable in a session. It is destroyed when that tf.Session.close.

In [41]:
my_tensor = tf.random_uniform((4,4),0,1)

In [42]:
my_var = tf.Variable(initial_value=my_tensor)

In [43]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


#### Note! You must initialize all global variables!

In [44]:
init = tf.global_variables_initializer()

In [45]:
init.run()

In [46]:
my_var.eval()

array([[0.2196126 , 0.39512467, 0.28654408, 0.6001202 ],
       [0.79863083, 0.39036572, 0.6812432 , 0.4329636 ],
       [0.14215529, 0.8374231 , 0.07159603, 0.07865739],
       [0.64187944, 0.83292234, 0.16483378, 0.82300854]], dtype=float32)

## 4. Placeholders

Placeholders are initially empty and are used to feed in the actual training examples.  
However they do need a declared expected data type (tf.float32) with a optional shape argument

In [48]:
ph = tf.placeholder(tf.float64)

In [49]:
ph = tf.placeholder(tf.int32)

In [50]:
ph = tf.placeholder(tf.float32,shape=(None,5))

## 5. TensorFlow Neural Network

![caption](img/snn1.png)

In [53]:
import numpy as np
import tensorflow as tf
np.random.seed(99)
tf.set_random_seed(99)

data

In [54]:
rand_a = np.random.uniform(0,100,(5,5))
rand_a

array([[67.22785586, 48.80783992, 82.5495174 ,  3.14463876, 80.80499634],
       [56.56174196, 29.76224987,  4.66957205, 99.06273995,  0.6825733 ],
       [76.97930282, 74.6767101 , 37.74389363, 49.41474522, 92.89483921],
       [39.54540443, 97.39562968, 52.44147154,  9.36130933, 81.33084128],
       [21.16867856, 55.43457846, 29.2269116 , 81.614236  , 82.80425662]])

In [55]:
rand_b = np.random.uniform(0,100,(5,1))
rand_b

array([[22.15773717],
       [64.48347016],
       [ 9.51816219],
       [41.16632388],
       [ 9.68652613]])

In [56]:
rand_a = np.random.uniform(0,100,(5,5))
rand_b = np.random.uniform(0,100,(5,1))

placeholder

In [57]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [59]:
add_op = tf.add(a,b)
mult_op = tf.multiply(a,b)

#### Running Sessions  to create Graphs with Feed Dictionaries

In [60]:
with tf.Session() as sess:
    add_result = sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
    print(add_result)
    
    print('\n')
    
    mult_result = sess.run(mult_op,feed_dict={a:rand_a,b:rand_b})
    print(mult_result)

[[ 98.15046  104.96898  131.41498   91.51074  107.25374 ]
 [ 43.934235 133.14336   98.50238   60.0336   136.16675 ]
 [125.82007   75.78715  124.09898  135.62555  151.67712 ]
 [168.62628  110.39762  181.96176  131.75821  111.54352 ]
 [ 62.84251   45.638046  28.277504  99.45092  101.82241 ]]


[[1206.0829   1777.1294   3991.9646    650.0109   1968.4766  ]
 [  28.360697 3889.2363   2390.0117    725.12396  4020.0857  ]
 [3881.9604    299.03827  3758.711    4584.1436   5733.617   ]
 [7108.0312   2150.7693   8243.339    3969.2903   2248.3242  ]
 [ 434.26544   298.26984   161.04051   723.64276   742.3886  ]]


#### Example Neural Network

In [61]:
n_features = 10
n_dense_neurons = 3

In [62]:
# Placeholder for x
x = tf.placeholder(tf.float32,(None,n_features))

In [63]:
# Variables for w and b
b = tf.Variable(tf.zeros([n_dense_neurons]))

W = tf.Variable(tf.random_normal([n_features,n_dense_neurons]))

Activation Function

In [64]:
xW = tf.matmul(x,W)

In [65]:
z = tf.add(xW,b)

In [66]:
a = tf.sigmoid(z)

init

In [67]:
init = tf.global_variables_initializer()

In [68]:
with tf.Session() as sess:
    sess.run(init)
    
    layer_out = sess.run(a,feed_dict={x : np.random.random([1,n_features])})

In [69]:
print(layer_out)

[[0.0971578  0.33739045 0.325781  ]]
