### vectorization

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [17]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("for loop version: " + str(1000*(toc-tic)) + "ms")

249856.805271
Vectorized version: 1.2829303741455078ms
249856.805271
for loop version: 422.8942394256592ms


In [2]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9],])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [7]:
cal = A.sum(axis=0)
cal

array([  59. ,  239. ,  155.4,   76.9])

In [9]:
percentage = A/cal.reshape(1,4)
percentage

array([[ 0.94915254,  0.        ,  0.02831403,  0.88426528],
       [ 0.02033898,  0.43514644,  0.33462033,  0.10403121],
       [ 0.03050847,  0.56485356,  0.63706564,  0.01170351]])

In [10]:
A/cal

array([[ 0.94915254,  0.        ,  0.02831403,  0.88426528],
       [ 0.02033898,  0.43514644,  0.33462033,  0.10403121],
       [ 0.03050847,  0.56485356,  0.63706564,  0.01170351]])

In [11]:
A + [1,2,3,4]

array([[  57. ,    2. ,    7.4,   72. ],
       [   2.2,  106. ,   55. ,   12. ],
       [   2.8,  137. ,  102. ,    4.9]])

In [14]:
a = np.random.rand(5)
a

array([ 0.59581991,  0.71488447,  0.89799716,  0.1312641 ,  0.91776446])

In [16]:
a.shape
# rank 1 array
# it's neither a row vector nor a column vector
# do not use in neural network

(5,)

In [17]:
a.T

array([ 0.59581991,  0.71488447,  0.89799716,  0.1312641 ,  0.91776446])

In [18]:
a.T.shape

(5,)

In [20]:
print(np.dot(a,a))
print(np.dot(a,a.T))

2.53198194568
2.53198194568


In [22]:
a = np.random.rand(5,1)
a

array([[ 0.61717651],
       [ 0.90622106],
       [ 0.23553724],
       [ 0.96729346],
       [ 0.31777663]])

In [23]:
a.T

array([[ 0.61717651,  0.90622106,  0.23553724,  0.96729346,  0.31777663]])

In [25]:
print(np.dot(a,a.T))

[[ 0.38090684  0.55929835  0.14536805  0.5969908   0.19612427]
 [ 0.55929835  0.8212366   0.21344881  0.8765817   0.28797587]
 [ 0.14536805  0.21344881  0.05547779  0.22783363  0.07484823]
 [ 0.5969908   0.8765817   0.22783363  0.93565664  0.30738326]
 [ 0.19612427  0.28797587  0.07484823  0.30738326  0.10098199]]


In [6]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)
c

[[ 1.00605216  0.67806667 -1.93842015]
 [-0.50082593  0.68506138 -1.04685239]
 [-0.523054    0.28385644 -0.53170546]]
[[ 1.38845452]
 [-0.59903198]
 [-1.73509381]]


array([[ 1.39685766,  0.94146473, -2.69140822],
       [ 0.30001075, -0.41037367,  0.62709805],
       [ 0.90754777, -0.49251756,  0.92255886]])

In [5]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 0, keepdims = True)
print(A)
print(B)

[[-0.28795816 -0.83236541 -0.33507943]
 [-1.70991549 -0.65216021  0.55167557]
 [ 0.24841642 -0.75759141  0.84381089]
 [ 0.23859695  1.04595195 -0.22546957]]
[[-1.51086028 -1.19616508  0.83493746]]


In [1]:
import numpy as np
import tensorflow as tf

In [2]:
w = tf.Variable(0, dtype=tf.float32)
cost = tf.add(tf.add(w**2, tf.multiply(-10.,w)), 25)